-- ThreatGuard upgrade: email -> email + URL + SMS scans.
-- ADDITIVE ONLY. No tables are dropped, recreated or renamed, and no existing row is modified.
-- Safe to run more than once. Run in the Supabase SQL Editor, BEFORE deploying the new backend.

-- 1. Which kind of content was scanned. Every existing row becomes 'email' via the column default.
alter table public.scans
  add column if not exists scan_type text not null default 'email';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'scans_scan_type_check' and conrelid = 'public.scans'::regclass
  ) then
    alter table public.scans
      add constraint scans_scan_type_check check (scan_type in ('email', 'url', 'sms'));
  end if;
end $$;

-- 2. A short display label used by history and the dashboard:
--    the subject for emails, the first 120 characters of the URL or message otherwise.
--    Generated by Postgres, so it also fills in for all existing rows.
--    (Adding a stored generated column rewrites the table once; on very large tables run it off-peak.)
alter table public.scans
  add column if not exists title text
  generated always as (left(coalesce(nullif(subject, ''), body), 120)) stored;

-- 3. History and dashboard filter by type per user.
create index if not exists scans_user_type_created_idx
  on public.scans (user_id, scan_type, created_at desc);

-- How URL and SMS scans use the existing columns (no other schema change needed):
--   url : body = the URL,          subject = '', sender = ''
--   sms : body = the message text, subject = '', sender = sender id / number (may be '')
--   `prediction` keeps its two values: 'phishing' means "threat" (phishing email, malicious URL or scam SMS), 'safe' otherwise.
--   Existing RLS policies already cover the new rows (they filter on user_id only).

-- Manual rollback, only if you ever need it (this deletes URL/SMS rows' type information, not email data):
--   drop index if exists public.scans_user_type_created_idx;
--   alter table public.scans drop column if exists title;
--   alter table public.scans drop constraint if exists scans_scan_type_check;
--   alter table public.scans drop column if exists scan_type;
